### ISSUE TITLE
A proposal, i guess

### ISSUE THREAD

**Issue by violetastcs** [gdelazzari/tech_api#1]
Hey, I am making a core API for more than just tech, but that was a subset of the core. Would you like to merge the projects together? My API is in really early development, however I am planning on adding
- An "ore dictionary" (Basically the one in Minecraft forge, when you create an item you specify it's "ore dictionary name". For example, if 2 mods had an item called copper, they do something like
`core.register_craftitem("mymod1:copper", {
	description = "copper",
	inventory_image = "mymod1_copper",
        ore_dict_name = "copper"
})` then any crafting recipe that uses one of the mod's coppers, then either one will work. I have got a small prototype of it but it's un-optimised for now

- The features that this API has for the most part
- Simpler, more uniform GUI API
- Some more that I can't be bothered listing here.

I feel like if both of the projects were merged into 1 the work flow would probably be faster (you could develop the tech-based part of it and I could develop the things that I had in mind.) and it would be simpler than having 2 separate APIs for different things. I hope you consider this option (even if now I will probably develop a layer of compatibility into my API so they don't conflict)

~ Jacob

EDIT 1, I forgot to mention my API would have somewhat of a pipe system, replacing the need for pipe works (although I would, again, make sure there would be a layer of compatibility)

**Comment by gdelazzari** [comment]
Hi, this sounds like a great idea! Actually, truth to be told, my plans for my project are similar to the ones you have for yours, so I think we're easing up our work by merging this together :) I would also love the idea of a uniform and better GUI, I didn't think about that before. However we'll need to get in touch and discuss about a couple of things (the pipe API for example) on something like IRC to ease things up. For example I don't feel like you should implement pipes in your core mod (I mean, you shouldn't register any node). I was thinking, for the item and fluid transport part, to provide an API that allows mods, for instance, to:

- declare that a node can accept items/fluids etc...
- ask the API whether or not a node can accept what a pipe is carrying (used in the *mod specific* transport code)

But the pipes are implemented *in the mods that use the API*, so there may be different mods with different pipes handling transport in different ways. The API (considering what I have in mind) would just make them connect and interact together seamlessly. Anyway this is just the idea I came up without thinking too much, so it's a point to discuss for sure.

You can join #minetest-technic so we can talk about this. Also in that channel you'll find the people that maintain Technic and Pipeworks, thus we can arrange a way to possibly keep these mods and make them compatible with our "thing" :)

**Comment by violetastcs** [comment]
@gdelazzari Yes! Although, if possible, could we talk on something other than IRC? For example discord? Because I don't really like IRC, it seems a bit alien to me. I can still use IRC if you need though!
