### ISSUE TITLE
Minetest's modstorage fails to load a big nodestore from disk

### ISSUE THREAD

**Issue by gdelazzari** [gdelazzari/tech_api#2]
Will need to find another way of permanently storing the nodestore submodule data

**Comment by cyian-1756** [comment]
I think this might be a bug in minetests json parsing, as the string that's failing to decode in minetest comes up as valid on pretty much every validator I can find online

**Comment by cyian-1756** [comment]
After some playing around I can say this is a bug in minetests json parsing. If I replace minetests built in json parser with cjson I can read nodestores that minetest fails to decode

**Comment by gdelazzari** [comment]
Interesting. Did you already open an issue on the minetest repo? However I think we will need another way to store the data anyway. If not using a DB then manual file writing will probably be the way to go.

**Comment by cyian-1756** [comment]
> Did you already open an issue on the minetest repo? 

Nope. I'll do that today

Edit: It looks like the latest version of MT from git has better debugging for these errors so I'm going to try that first

Edit_2: report [here](https://github.com/minetest/minetest/issues/6565)

> If not using a DB then manual file writing will probably be the way to go.

This reminds me, I was looking into it a bit and you can use sqlite and other libraries that are just C wrappers so long as you either disable mod security or are a trusted mod

**Comment by cyian-1756** [comment]
Hey after some debugging I managed to get saving and loading networks to work by using flatDB (And replacing all require()s with loadfile()s). My only issue at this point is that mod security needs to be turned off because flatDB needs to write to various files 

Once I figure out how to get around that I'll make a PR with my changes

**Comment by gdelazzari** [comment]
Wow, cool! I was looking right now into a solution, and got almost tempted to write a custom DB from scratch, specific for our needs :D 
The issue you're probably dealing with is

> (...) the following things shouldn't work: (...)
-Reading/writing to anywhere outside the world directory or your mod directory.
-Reading/writing to anywhere in your mod directory after the init stage. (this is a limitation of the way that minetest implements mods. A workaround is to open all files that you will need at startup and use the file descriptors later. Note that you should never write in your mod directory though, only read; the mod directory is not always writable. Use the world directory if you have to save something)

as reported here https://forum.minetest.net/viewtopic.php?t=12471, right?

Maybe we could get in touch on discord or IRC and brainstorm something, my time is limited but I should be able to find a couple of hours a day to chat and do some research if needed

**Comment by cyian-1756** [comment]
> as reported here https://forum.minetest.net/viewtopic.php?t=12471, right?

Yup, writing to the current world dir works fine, only issue now is that the database folder needs to be created if it doesn't exist 

> Maybe we could get in touch on discord or IRC and brainstorm something

sure which do you prefer?

**Comment by cyian-1756** [comment]
Could we chat on glitter.im? I;m already all set up there

**Comment by gdelazzari** [comment]
Never heard of that, but by looking at the website looks promising, so let's go for it :) I just logged in, but I guess I'll need an invite link or something, just tell me what to do

**Comment by gdelazzari** [comment]
Closed by commits c4c090f8de15e22412e3c0f4fa12eb0b72b88e7c & ae94565d83ac732c83a5c2ff66afe6521dfc5575
