### ISSUE TITLE
Some times crashes when removing nodes from a network

### ISSUE THREAD

**Issue by cyian-1756** [gdelazzari/tech_api#3]
Sometimes when removing nodes from a network the game crashes with the following error

AsyncErr: environment_Step: Runtime error from mod 'tech_api' in callback environment_Step()
:/home/USER/.minetest/mods/tech_api/energy/distribution.lua:213: attempt to perform arithmetic on a string value

stack traceback:
/home/USER/.minetest/mods/tech_api/energy/distribution.lua:213: in function 'distribution_cycle

The offending lines of code are 

```if available < 0 then
        -- this should NEVER happen
        tech_api.utils.log.print('warning', "network #" .. id .. " gained " + (-available) .. " for free")
```

Where it seems you uses a + where you should have used a ..

Edit 2: Yup replacing the + with .. fixes this

**Comment by gdelazzari** [comment]
Thanks! That code, as the comment says, shouldn't run at all and maybe this is why that error never happened to me. How did you trigger that exactly? I swear I removed a ton of nodes while testing the mod and it never happened... Thanks for the fix BTW, unfortunately I have almost no time to continue working on this project, but seeing someone taking notice and contributing is really nice!

**Comment by cyian-1756** [comment]
> How did you trigger that exactly?

I dug a bunch of nodes that were in a network while in creative mode (It seems to trigger most often when removing nodes that consume power)
