### ISSUE TITLE
Nil checks needed in api.lua

### ISSUE THREAD

**Issue by cyian-1756** [gdelazzari/tech_api#6]
I've found that some times `tech_api.utils.nodestore.data` will fail to return anything (Because of me messing up, not a bug) and that causes the mod to crash at line 208 in api.lua `local is_transporter = tech_api.energy.has_definition_for_group(nd_def.node_name, 'transporter')`

**Comment by gdelazzari** [comment]
This is 99% caused by the nodestore getting out of sync with the world. Nevertheless some checks are to be implemented indeed, even after a stable nodestore solution will be implemented
